env:
  node: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - "*.test.js"
rules:
  no-underscore-dangle: 'off'
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always

